spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devapix_catalog_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api-catalog
  port: 8082
  forward-headers-strategy: framework

logging:
  level:
    devapix.api_catalog_service: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-catalog.log
